# Generated by Django 5.1.1 on 2024-09-24 14:40

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True, default='-----')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('min_experience', models.PositiveIntegerField(default=0)),
                ('max_experience', models.PositiveIntegerField(default=0)),
                ('openings', models.PositiveIntegerField()),
                ('min_package', models.PositiveIntegerField(default=0)),
                ('max_package', models.PositiveIntegerField(default=0)),
                ('skills', models.TextField()),
                ('education', models.CharField(max_length=255)),
                ('work_mode', models.CharField(choices=[('hybrid', 'Hybrid'), ('remote', 'Remote'), ('office', 'Office')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='sdeuser789', max_length=150, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone number')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('current_address', models.TextField(blank=True, null=True, verbose_name='Current address')),
                ('state', models.CharField(default='ap', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='JobSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveIntegerField()),
                ('experience', models.IntegerField(choices=[(0, '0 Fresher'), (1, '1 Year'), (2, '2 Years'), (3, '3 Years'), (4, '4 Years'), (5, '5+ Years')])),
                ('resume', models.FileField(upload_to='resumes/')),
                ('result', models.CharField(blank=True, choices=[('shortlisted', 'Shortlisted'), ('not_shortlisted', 'Not Shortlisted')], default='Pending', max_length=20)),
                ('user_has_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('SoftwareJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobportal.softwarejob')),
            ],
        ),
    ]
